### ISSUE TITLE
there is a problem in code line number 7

### ISSUE THREAD

**Issue by Gouravmhatre** [Gouravmhatre/DevOps#1]
Hii team, i found there is a bug in code please this corrected ASAP.

**Comment by bipeensinha** [comment]
Sire Mr.PM i am woeking on it

**Comment by Gouravmhatre** [comment]
thank you keep me updated.

**Comment by bipeensinha** [comment]
Issues has been fixed , i ffix below line nu
![a](https://user-images.githubusercontent.com/49720823/110884379-09f71a00-830b-11eb-82d3-e235a408b4a5.png)
mber

**Comment by Gouravmhatre** [comment]
thank you
